name: BariPort
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    version: 4.9.0
configs:
  Debug: debug
  Release: release
schemes:
  BariPort(Debug):
    templates:
      - BariApp
    run:
      config: Debug
    archive:
      config: Debug
  BariPort(Release):
    templates:
      - BariApp
    run:
      config: Release
    archive:
      config: Release      
  UIComponents:
    build:
      targets:
        UIComponents: all    
schemeTemplates:
  BariApp:
    build:
      targets:
        BariPort: all
    run:
      language: ja
      region: JP
settings:
  base:
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: YES   
    MARKETING_VERSION: ${APP_VERSION}
    CURRENT_PROJECT_VERSION: 1            
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UIUserInterfaceStyle: Light
    SDKROOT: iphoneos
  configs:
    Debug:
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      RUN_DOCUMENTATION_COMPILER: Yes
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEVELOP DEBUG_BUILD
    Release:      
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      RUN_DOCUMENTATION_COMPILER: NO
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE RELEASE_BUILD
options:
  deploymentTarget:
    iOS: 16.0  
  defaultConfig: Debug
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  developmentLanguage: ja  
targets:
  BariPort:
    platform: iOS
    dependencies:
      - target: UIComponents
      - target: BariPortAPI
    settings:
      base:
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO        
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.social-networking
        PRODUCT_NAME: BariPort
        TARGETED_DEVICE_FAMILY: 1
        INFOPLIST_KEY_CFBundleDisplayName: BariPort
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_FILE: BariPort/Info-Release.plist          
        MARKETING_VERSION: ${APP_VERSION}
        CURRENT_PROJECT_VERSION: 1        
      configs:
        Debug:
          INFOPLIST_KEY_CFBundleDisplayName: BariPort(Debug)
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
          INFOPLIST_FILE: BariPort/Info-Debug.plist          
          PRODUCT_BUNDLE_IDENTIFIER: jp.japan-connect-hackathon.develop.BariPort
          SWIFT_VERSION: '5.0'
        Release:
          INFOPLIST_KEY_CFBundleDisplayName: BariPort(Debug)      
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
          INFOPLIST_FILE: BariPort/Info-Release.plist          
          PRODUCT_BUNDLE_IDENTIFIER: jp.japan-connect-hackathon.release.BariPort
          SWIFT_VERSION: '5.0'
    sources:
    - name: BariPort
      path: BariPort
    type: application
  BariPortTests:
    dependencies:
    - target: BariPort
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: jp.japan-connect-hackathon.BariPortTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/BariPort.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/BariPort
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: jp.japan-connect-hackathon.BariPortTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/BariPort.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/BariPort
    sources:
    - name: BariPortTests
      path: BariPortTests
    type: bundle.unit-test
  BariPortUITests:
    dependencies:
    - target: BariPort
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: jp.japan-connect-hackathon.BariPortUITests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_TARGET_NAME: BariPort
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: jp.japan-connect-hackathon.BariPortUITests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_TARGET_NAME: BariPort
    sources:
    - name: BariPortUITests
      path: BariPortUITests
    type: bundle.ui-testing
  BariPortAPI:
    dependencies:
    - package: Alamofire
    type: framework
    platform: iOS
    info:
      path: BariPortAPI/info.plist
    sources:
      - path: BariPortAPI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.japan-connect-hackathon.BariPortAPI
  UIComponents:
    type: framework
    platform: iOS
    info:
      path: UIComponents/info.plist
    sources:
      - path: UIComponents
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.japan-connect-hackathon.UIComponents
    
    
